### ISSUE TITLE
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by ishandutta2007** [vsuthichai/paraphraser#10]
ishandutta2007@MacBook-Pro:~/Documents/Projects/paraphraser/paraphraser$ `python inference.py --checkpoint=../checkpoint_path/train-20180325-001253/model-171856 `

> /Users/ishandutta2007/.pyenv/versions/3.5.0/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expect
>   return f(*args, **kwds)
> /Users/ishandutta2007/.pyenv/versions/3.5.0/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expect
>   return f(*args, **kwds)
> /Users/ishandutta2007/.pyenv/versions/3.5.0/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expect
>   return f(*args, **kwds)
> Traceback (most recent call last):
>   File "inference.py", line 3, in <module>
>     from preprocess_data import preprocess_batch
>   File "/Users/ishandutta2007/Documents/Projects/paraphraser/paraphraser/preprocess_data.py", line 23, in <module>
>     from nlp_pipeline import openmp_nlp_pipeline
>   File "/Users/ishandutta2007/Documents/Projects/paraphraser/paraphraser/nlp_pipeline.py", line 7, in <module>
>     nlp = spacy.load('en')
>   File "/Users/ishandutta2007/.pyenv/versions/3.5.0/lib/python3.5/site-packages/spacy/__init__.py", line 21, in load
>     return util.load_model(name, **overrides)
>   File "/Users/ishandutta2007/.pyenv/versions/3.5.0/lib/python3.5/site-packages/spacy/util.py", line 119, in load_model
>     raise IOError(Errors.E050.format(name=name))
> OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
> 
>

**Comment by wwwehr** [comment]
try these to stage the proper files:
```
python -m spacy download en_core_web_sm
python -m spacy download en
```
