### ISSUE TITLE
how to run the paraphraser? meet with some problem

### ISSUE THREAD

**Issue by terryqj0107** [vsuthichai/paraphraser#6]
Traceback (most recent call last):
  File "inference.py", line 3, in <module>
    from preprocess_data import preprocess_batch
  File "/data/jquan/codes/paraphraser-master/paraphraser/preprocess_data.py", line 26, in <module>
    word_to_id, idx_to_word, embedding, start_id, end_id, unk_id, mask_id = load_sentence_embeddings()
  File "/data/jquan/codes/paraphraser-master/paraphraser/embeddings.py", line 9, in load_sentence_embeddings
    with open("../../para-nmt-50m/data/ngram-word-concat-40.pickle", 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../para-nmt-50m/data/ngram-word-concat-40.pickle'

**Comment by wwwehr** [comment]
you need to download and stage [this zip file](https://doc-0k-58-docs.googleusercontent.com/docs/securesc/t80p32i24nganbvup2ql529kf29nrh3u/cp1vce1dlt48k4h0kfofcrkmjn4rna93/1551729600000/07054651981434771333/06613463653097052731/1l2liCZqWX3EfYpzv9OmVatJAEISPFihW?e=download)

**Comment by rtatay** [comment]
Had the same issue...got a HTTP 403 error access denied when trying the link. :(

**Comment by Dobatymo** [comment]
Try this one https://drive.google.com/file/d/1l2liCZqWX3EfYpzv9OmVatJAEISPFihW/view?usp=sharing

**Comment by afriedman412** [comment]
does anyone have a mirror for the zip or has it been re-upped somewhere?

it's over download cap rn!

**Comment by sohailhaider** [comment]
If anyone you guys have the data model please share the link here, none of the above links are operational.

**Comment by cstan969** [comment]
The link for nmt-50m-demo on this website worked for me:  https://www.cs.cmu.edu/~jwieting/

Here's the extracted hyperlink as well:
https://drive.google.com/file/d/1l2liCZqWX3EfYpzv9OmVatJAEISPFihW/view?usp=sharing
